name: lets_build_planner
description: "A content planning calendar app with Supabase integration for organizing and scheduling your content with privacy controls."
publish_to: "none"
version: 1.0.0+3

environment:
  sdk: ^3.6.0

dependencies:
  googleapis: ^14.0.0
  google_sign_in: 6.2.1
  http: ^1.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  intl: 0.20.2
  uuid: ^4.0.0
  supabase_flutter: '>=1.10.0'
  app_links: ^6.0.0
  file_picker: '>=8.1.2'
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Delight
      fonts:
        - asset: assets/fonts/Delight-Thin.ttf
          weight: 100
        - asset: assets/fonts/Delight-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Delight-Light.ttf
          weight: 300
        - asset: assets/fonts/Delight-Regular.ttf
          weight: 400
        - asset: assets/fonts/Delight-Medium.ttf
          weight: 500
        - asset: assets/fonts/Delight-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Delight-Bold.ttf
          weight: 700
        - asset: assets/fonts/Delight-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Delight-Black.ttf
          weight: 900
